### ISSUE TITLE
[Feature] Filter replications by status

### ISSUE THREAD

**Issue by jcace** [application-research/delta-ui#84]
Currently the UI doesn't provide any way to filter the replications by their `status`. 

![Image](https://github.com/application-research/delta-ui/assets/12418265/f8a27f26-7071-4268-888e-3f51a4411c6e)

The API allows specifying `statuses`, so we need to add a search box for this and wire it up to the API - https://github.com/application-research/delta-dm/blob/main/docs/api.md#get-replications

**Comment by elijaharita** [comment]
man this is quite a layout puzzle. i'm planning to make it 3 checkboxes so u can mix and match which settings you want to enabled, but having a really hard time trying to fit it into the whole layout

i might try moving each config option into popouts that you can click to open up and do the settings there. and maybe that would give room to show an on/off signal next to the popout button for whether a filter is actually in effect for each option?

or maybe i just need to find a better spot to put the filter menu? a sidebar might be better than putting everything on the top because most of the form fields are meant for a more vertical placement in comparison to the really wide box we have now.

i dunno i shall think about it

**Comment by jcace** [comment]
@elijaharita , oh the Status should be freeform text - it is no longer just PENDING/SUCCESS/FAILURE as we're now pulling in the statuses from the deal on chain. It could eventually become a dropdown, but for now just make it a freeform text field. 

In terms of layout, maybe split the space that's currently taken up by the "Message" input box in half and use that space? Message doesn't need to be as wide as it is

**Comment by elijaharita** [comment]
> @elijaharita , oh the Status should be text, not checkboxes - it is no longer just PENDING/SUCCESS/FAILURE as we're now pulling in the statuses from the deal on chain. It could eventually become a dropdown, but for now just make it a freeform text field. 
> 
> In terms of layout, maybe split the space that's currently taken up by the "Message" input box in half and use that space? Message doesn't need to be as wide as it is 

ah ok, that makes things a lot easier. on it
